[package]
name = "sheet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.4"
csv = "1.2.2"
libc = "0.2.148"
rand = "0.8.5"
termios = "0.3.3"
